modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="dinosaurium"
version="1.4.0"
displayName="Dinosaurium"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Yumithirritj"
description="Adds Mesozoic features-n-creatures to Minecraft"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dinosaurium]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dinosaurium]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.dinosaurium]]
    modId="geckolib"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration