
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.dinosaurium.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;

import com.dinosaurium.item.ZhenyuanlongFossilItem;
import com.dinosaurium.item.ZbyFossilItem;
import com.dinosaurium.item.YutyrannusFossilItem;
import com.dinosaurium.item.WoodenKnifeItem;
import com.dinosaurium.item.WaterCupItem;
import com.dinosaurium.item.VelociraptorFossilItem;
import com.dinosaurium.item.UnindentifiedFossilItem;
import com.dinosaurium.item.UnfiredTeacupItem;
import com.dinosaurium.item.UnboiledLaurozamitesTeaItem;
import com.dinosaurium.item.TyrannosaurusFossilItem;
import com.dinosaurium.item.TuojiangosaurusFossilItem;
import com.dinosaurium.item.TricepatopsFossilItem;
import com.dinosaurium.item.TinIngotItem;
import com.dinosaurium.item.TimeMachineItem;
import com.dinosaurium.item.TherizinosaurusFossilItem;
import com.dinosaurium.item.TeacupItem;
import com.dinosaurium.item.StoneKnifeItem;
import com.dinosaurium.item.StegosaurusFossilItem;
import com.dinosaurium.item.SpinosaurusFossilItem;
import com.dinosaurium.item.SinosauropteryxFossilItem;
import com.dinosaurium.item.SinewItem;
import com.dinosaurium.item.ShuvuuiaFossilItem;
import com.dinosaurium.item.SharovipteryxFossilItem;
import com.dinosaurium.item.SawfishSwordItem;
import com.dinosaurium.item.RepenomamusFossilItem;
import com.dinosaurium.item.RawTinItem;
import com.dinosaurium.item.RawOysterItem;
import com.dinosaurium.item.RawOrnithomimosaurItem;
import com.dinosaurium.item.QuetzalcoatlusFossilItem;
import com.dinosaurium.item.PycnofiberItem;
import com.dinosaurium.item.PterodaustroFossilItem;
import com.dinosaurium.item.PteranodonFossilItem;
import com.dinosaurium.item.PsittacosaurusFossilItem;
import com.dinosaurium.item.ProtoceratopsFossilItem;
import com.dinosaurium.item.ParasaurolophusFossilItem;
import com.dinosaurium.item.ParapuzosiaFossilItem;
import com.dinosaurium.item.PachyrhinosaurusFossilItem;
import com.dinosaurium.item.PachycephalosaurusFossilItem;
import com.dinosaurium.item.OysterSoupItem;
import com.dinosaurium.item.OviraptorFossilItem;
import com.dinosaurium.item.OuranosaurusFossilItem;
import com.dinosaurium.item.OsmundaRootItem;
import com.dinosaurium.item.OsmundaBreadItem;
import com.dinosaurium.item.OrodromeusFossilItem;
import com.dinosaurium.item.OnchopristisFossilItem;
import com.dinosaurium.item.OmmaItemItem;
import com.dinosaurium.item.OlorotitanFossilItem;
import com.dinosaurium.item.NyctosaurusFossilItem;
import com.dinosaurium.item.NigersaurusFossilItem;
import com.dinosaurium.item.NetheriteKnifeItem;
import com.dinosaurium.item.NemegtosaurusFossilItem;
import com.dinosaurium.item.NanuqsaurusFossilItem;
import com.dinosaurium.item.NannogomphusItemItem;
import com.dinosaurium.item.MongolarachneItemItem;
import com.dinosaurium.item.MongolarachneFossilItem;
import com.dinosaurium.item.MiragaiaFossilItem;
import com.dinosaurium.item.MicroraptorFossilItem;
import com.dinosaurium.item.MashedBugsItem;
import com.dinosaurium.item.MamenchisaurusFossilItem;
import com.dinosaurium.item.MagyarosaurusFossilItem;
import com.dinosaurium.item.LisowiciaFossilItem;
import com.dinosaurium.item.LaurozamitesTeaItem;
import com.dinosaurium.item.LaurozamitesLeavesItem;
import com.dinosaurium.item.LambeosaurusFossilItem;
import com.dinosaurium.item.JeholopterusFossilItem;
import com.dinosaurium.item.IronKnifeItem;
import com.dinosaurium.item.IguanodonFossilItem;
import com.dinosaurium.item.IchthyosaurusFossilItem;
import com.dinosaurium.item.HorseshoeCrabBloodItem;
import com.dinosaurium.item.HerrerasaurusFossilItem;
import com.dinosaurium.item.HatzegopteryxFossilItem;
import com.dinosaurium.item.HalszkaraptorFossilItem;
import com.dinosaurium.item.GoldenKnifeItem;
import com.dinosaurium.item.GiantCicadItemItem;
import com.dinosaurium.item.GallimimusFossilItem;
import com.dinosaurium.item.FriedSpiderItem;
import com.dinosaurium.item.EdmontosaurusFossilItem;
import com.dinosaurium.item.DsungaripterusFossilItem;
import com.dinosaurium.item.DiplodocusFossilItem;
import com.dinosaurium.item.DilophosaurusFossilItem;
import com.dinosaurium.item.DiamondKnifeItem;
import com.dinosaurium.item.DeinocheirusFossilItem;
import com.dinosaurium.item.CretaraneusItemItem;
import com.dinosaurium.item.CretaraneusFossilItem;
import com.dinosaurium.item.CrassostreaOysterItem;
import com.dinosaurium.item.CookedOrnithomimosaurItem;
import com.dinosaurium.item.CompsognathusFossilItem;
import com.dinosaurium.item.CoelophysisFossilItem;
import com.dinosaurium.item.CephaloleichnitesItemItem;
import com.dinosaurium.item.CephaloleichnitesFossilItem;
import com.dinosaurium.item.BugNetItem;
import com.dinosaurium.item.BruhathkayosaurusFossilItem;
import com.dinosaurium.item.BronzeSwordItem;
import com.dinosaurium.item.BronzeShovelItem;
import com.dinosaurium.item.BronzePickaxeItem;
import com.dinosaurium.item.BronzeKnifeItem;
import com.dinosaurium.item.BronzeIngotItem;
import com.dinosaurium.item.BronzeHoeItem;
import com.dinosaurium.item.BronzeAxeItem;
import com.dinosaurium.item.BronzeArmorItem;
import com.dinosaurium.item.BrachytrachelopanFossilItem;
import com.dinosaurium.item.BeipiaosaurusFossilItem;
import com.dinosaurium.item.BauxiteItem;
import com.dinosaurium.item.BaryonyxFossilItem;
import com.dinosaurium.item.AustroraptorFossilItem;
import com.dinosaurium.item.ArchaeopteryxFossilItem;
import com.dinosaurium.item.AramourgianiaFossilItem;
import com.dinosaurium.item.AnzuFossilItem;
import com.dinosaurium.item.AnkylosaurusFossilItem;
import com.dinosaurium.item.AnchiornisFossilItem;
import com.dinosaurium.item.AmberItem;
import com.dinosaurium.item.AmberFossilItem;
import com.dinosaurium.item.AmargasaurusFossilItem;
import com.dinosaurium.item.AluminiumNuggetItem;
import com.dinosaurium.item.AluminiumIngotItem;
import com.dinosaurium.DinosauriumMod;

public class DinosauriumModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(DinosauriumMod.MODID);
	public static final DeferredItem<Item> VELOCIRAPTOR_SPAWN_EGG = REGISTRY.register("velociraptor_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.VELOCIRAPTOR, -5400466, -2697514, new Item.Properties()));
	public static final DeferredItem<Item> SHUVUUIA_SPAWN_EGG = REGISTRY.register("shuvuuia_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.SHUVUUIA, -14671840, -3623793, new Item.Properties()));
	public static final DeferredItem<Item> AUSTRORAPTOR_SPAWN_EGG = REGISTRY.register("austroraptor_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.AUSTRORAPTOR, -11318853, -2434342, new Item.Properties()));
	public static final DeferredItem<Item> DIPLODOCUS_SPAWN_EGG = REGISTRY.register("diplodocus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.DIPLODOCUS, -4683178, -12833764, new Item.Properties()));
	public static final DeferredItem<Item> QUETZALCOATLUS_SPAWN_EGG = REGISTRY.register("quetzalcoatlus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.QUETZALCOATLUS, -11316370, -1, new Item.Properties()));
	public static final DeferredItem<Item> MICRORAPTOR_SPAWN_EGG = REGISTRY.register("microraptor_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.MICRORAPTOR, -16053220, -15725240, new Item.Properties()));
	public static final DeferredItem<Item> HATZEGOPTERYX_SPAWN_EGG = REGISTRY.register("hatzegopteryx_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.HATZEGOPTERYX, -8029060, -12514292, new Item.Properties()));
	public static final DeferredItem<Item> ARAMBOURGIANIA_SPAWN_EGG = REGISTRY.register("arambourgiania_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ARAMBOURGIANIA, -6387870, -10927572, new Item.Properties()));
	public static final DeferredItem<Item> AMBER = REGISTRY.register("amber", AmberItem::new);
	public static final DeferredItem<Item> AMBER_ORE = block(DinosauriumModBlocks.AMBER_ORE);
	public static final DeferredItem<Item> AMBER_BLOCK = block(DinosauriumModBlocks.AMBER_BLOCK);
	public static final DeferredItem<Item> DEEPSLATE_AMBER_ORE = block(DinosauriumModBlocks.DEEPSLATE_AMBER_ORE);
	public static final DeferredItem<Item> ICHTHYOSAURUS_SPAWN_EGG = REGISTRY.register("ichthyosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ICHTHYOSAURUS, -12698023, -12500402, new Item.Properties()));
	public static final DeferredItem<Item> ANKYLOSAURUS_SPAWN_EGG = REGISTRY.register("ankylosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ANKYLOSAURUS, -9610680, -13226199, new Item.Properties()));
	public static final DeferredItem<Item> GALLIMIMUS_SPAWN_EGG = REGISTRY.register("gallimimus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.GALLIMIMUS, -7504289, -13554913, new Item.Properties()));
	public static final DeferredItem<Item> DEINOCHEIRUS_SPAWN_EGG = REGISTRY.register("deinocheirus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.DEINOCHEIRUS, -4276546, -13027015, new Item.Properties()));
	public static final DeferredItem<Item> RAW_ORNITHOMIMOSAUR = REGISTRY.register("raw_ornithomimosaur", RawOrnithomimosaurItem::new);
	public static final DeferredItem<Item> COOKED_ORNITHOMIMOSAUR = REGISTRY.register("cooked_ornithomimosaur", CookedOrnithomimosaurItem::new);
	public static final DeferredItem<Item> STEGOSAURUS_SPAWN_EGG = REGISTRY.register("stegosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.STEGOSAURUS, -4808108, -9418449, new Item.Properties()));
	public static final DeferredItem<Item> TRICERATOPS_SPAWN_EGG = REGISTRY.register("triceratops_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.TRICERATOPS, -7705531, -11123412, new Item.Properties()));
	public static final DeferredItem<Item> TYRANNOSAURUS_SPAWN_EGG = REGISTRY.register("tyrannosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.TYRANNOSAURUS, -12767929, -6521251, new Item.Properties()));
	public static final DeferredItem<Item> ONCHOPRISTIS_SPAWN_EGG = REGISTRY.register("onchopristis_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ONCHOPRISTIS, -11451854, -1, new Item.Properties()));
	public static final DeferredItem<Item> SPINOSAURUS_SPAWN_EGG = REGISTRY.register("spinosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.SPINOSAURUS, -11716826, -3163296, new Item.Properties()));
	public static final DeferredItem<Item> AMARGASAURUS_SPAWN_EGG = REGISTRY.register("amargasaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.AMARGASAURUS, -11502028, -4220036, new Item.Properties()));
	public static final DeferredItem<Item> SAWFISH_SWORD = REGISTRY.register("sawfish_sword", SawfishSwordItem::new);
	public static final DeferredItem<Item> THERIZINOSAURUS_SPAWN_EGG = REGISTRY.register("therizinosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.THERIZINOSAURUS, -9347251, -8692387, new Item.Properties()));
	public static final DeferredItem<Item> PARASAUROLOPHUS_SPAWN_EGG = REGISTRY.register("parasaurolophus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PARASAUROLOPHUS, -6520483, -11646394, new Item.Properties()));
	public static final DeferredItem<Item> SINOSAUROPTERYX_SPAWN_EGG = REGISTRY.register("sinosauropteryx_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.SINOSAUROPTERYX, -7114950, -1, new Item.Properties()));
	public static final DeferredItem<Item> NIGERSAURUS_SPAWN_EGG = REGISTRY.register("nigersaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.NIGERSAURUS, -8959157, -6192253, new Item.Properties()));
	public static final DeferredItem<Item> IGUANODON_SPAWN_EGG = REGISTRY.register("iguanodon_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.IGUANODON, -9265561, -1315861, new Item.Properties()));
	public static final DeferredItem<Item> COMPSOGNATHUS_SPAWN_EGG = REGISTRY.register("compsognathus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.COMPSOGNATHUS, -4550301, -6587049, new Item.Properties()));
	public static final DeferredItem<Item> OVIRAPTOR_SPAWN_EGG = REGISTRY.register("oviraptor_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.OVIRAPTOR, -10460303, -12762745, new Item.Properties()));
	public static final DeferredItem<Item> PTERANODON_SPAWN_EGG = REGISTRY.register("pteranodon_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PTERANODON, -9857371, -2651093, new Item.Properties()));
	public static final DeferredItem<Item> BRUHATHKAYOSAURUS_SPAWN_EGG = REGISTRY.register("bruhathkayosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.BRUHATHKAYOSAURUS, -13743314, -8044737, new Item.Properties()));
	public static final DeferredItem<Item> NYCTOSAURUS_SPAWN_EGG = REGISTRY.register("nyctosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.NYCTOSAURUS, -3355444, -5126964, new Item.Properties()));
	public static final DeferredItem<Item> BRACHYTRACHELOPAN_SPAWN_EGG = REGISTRY.register("brachytrachelopan_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.BRACHYTRACHELOPAN, -10794456, -5376, new Item.Properties()));
	public static final DeferredItem<Item> VELOCIRAPTOR_FOSSIL = REGISTRY.register("velociraptor_fossil", VelociraptorFossilItem::new);
	public static final DeferredItem<Item> SHUVUUIA_FOSSIL = REGISTRY.register("shuvuuia_fossil", ShuvuuiaFossilItem::new);
	public static final DeferredItem<Item> AUSTRORAPTOR_FOSSIL = REGISTRY.register("austroraptor_fossil", AustroraptorFossilItem::new);
	public static final DeferredItem<Item> DIPLODOCUS_FOSSIL = REGISTRY.register("diplodocus_fossil", DiplodocusFossilItem::new);
	public static final DeferredItem<Item> QUETZALCOATLUS_FOSSIL = REGISTRY.register("quetzalcoatlus_fossil", QuetzalcoatlusFossilItem::new);
	public static final DeferredItem<Item> MICRORAPTOR_FOSSIL = REGISTRY.register("microraptor_fossil", MicroraptorFossilItem::new);
	public static final DeferredItem<Item> HATZEGOPTERYX_FOSSIL = REGISTRY.register("hatzegopteryx_fossil", HatzegopteryxFossilItem::new);
	public static final DeferredItem<Item> ARAMOURGIANIA_FOSSIL = REGISTRY.register("aramourgiania_fossil", AramourgianiaFossilItem::new);
	public static final DeferredItem<Item> ICHTHYOSAURUS_FOSSIL = REGISTRY.register("ichthyosaurus_fossil", IchthyosaurusFossilItem::new);
	public static final DeferredItem<Item> ANKYLOSAURUS_FOSSIL = REGISTRY.register("ankylosaurus_fossil", AnkylosaurusFossilItem::new);
	public static final DeferredItem<Item> GALLIMIMUS_FOSSIL = REGISTRY.register("gallimimus_fossil", GallimimusFossilItem::new);
	public static final DeferredItem<Item> DEINOCHEIRUS_FOSSIL = REGISTRY.register("deinocheirus_fossil", DeinocheirusFossilItem::new);
	public static final DeferredItem<Item> STEGOSAURUS_FOSSIL = REGISTRY.register("stegosaurus_fossil", StegosaurusFossilItem::new);
	public static final DeferredItem<Item> TRICEPATOPS_FOSSIL = REGISTRY.register("tricepatops_fossil", TricepatopsFossilItem::new);
	public static final DeferredItem<Item> TYRANNOSAURUS_FOSSIL = REGISTRY.register("tyrannosaurus_fossil", TyrannosaurusFossilItem::new);
	public static final DeferredItem<Item> SPINOSAURUS_FOSSIL = REGISTRY.register("spinosaurus_fossil", SpinosaurusFossilItem::new);
	public static final DeferredItem<Item> AMARGASAURUS_FOSSIL = REGISTRY.register("amargasaurus_fossil", AmargasaurusFossilItem::new);
	public static final DeferredItem<Item> THERIZINOSAURUS_FOSSIL = REGISTRY.register("therizinosaurus_fossil", TherizinosaurusFossilItem::new);
	public static final DeferredItem<Item> PARASAUROLOPHUS_FOSSIL = REGISTRY.register("parasaurolophus_fossil", ParasaurolophusFossilItem::new);
	public static final DeferredItem<Item> SINOSAUROPTERYX_FOSSIL = REGISTRY.register("sinosauropteryx_fossil", SinosauropteryxFossilItem::new);
	public static final DeferredItem<Item> NIGERSAURUS_FOSSIL = REGISTRY.register("nigersaurus_fossil", NigersaurusFossilItem::new);
	public static final DeferredItem<Item> IGUANODON_FOSSIL = REGISTRY.register("iguanodon_fossil", IguanodonFossilItem::new);
	public static final DeferredItem<Item> COMPSOGNATHUS_FOSSIL = REGISTRY.register("compsognathus_fossil", CompsognathusFossilItem::new);
	public static final DeferredItem<Item> OVIRAPTOR_FOSSIL = REGISTRY.register("oviraptor_fossil", OviraptorFossilItem::new);
	public static final DeferredItem<Item> PTERANODON_FOSSIL = REGISTRY.register("pteranodon_fossil", PteranodonFossilItem::new);
	public static final DeferredItem<Item> PACHYCEPHALOSAURUS_FOSSIL = REGISTRY.register("pachycephalosaurus_fossil", PachycephalosaurusFossilItem::new);
	public static final DeferredItem<Item> BRUHATHKAYOSAURUS_FOSSIL = REGISTRY.register("bruhathkayosaurus_fossil", BruhathkayosaurusFossilItem::new);
	public static final DeferredItem<Item> NYCTOSAURUS_FOSSIL = REGISTRY.register("nyctosaurus_fossil", NyctosaurusFossilItem::new);
	public static final DeferredItem<Item> BRACHYTRACHELOPAN_FOSSIL = REGISTRY.register("brachytrachelopan_fossil", BrachytrachelopanFossilItem::new);
	public static final DeferredItem<Item> UNIDENTIFIED_FOSSIL = REGISTRY.register("unidentified_fossil", UnindentifiedFossilItem::new);
	public static final DeferredItem<Item> PALAEONTOLOGY_TABLE = block(DinosauriumModBlocks.PALAEONTOLOGY_TABLE);
	public static final DeferredItem<Item> DEEPSLATE_FOSSIL_BLOCK = block(DinosauriumModBlocks.DEEPSLATE_FOSSIL_BLOCK);
	public static final DeferredItem<Item> FOSSIL_BLOCK = block(DinosauriumModBlocks.FOSSIL_BLOCK);
	public static final DeferredItem<Item> MIRAGAIA_FOSSIL = REGISTRY.register("miragaia_fossil", MiragaiaFossilItem::new);
	public static final DeferredItem<Item> HORSETAIL = block(DinosauriumModBlocks.HORSETAIL);
	public static final DeferredItem<Item> TALL_HORSETAIL = doubleBlock(DinosauriumModBlocks.TALL_HORSETAIL);
	public static final DeferredItem<Item> MIRAGAIA_SPAWN_EGG = REGISTRY.register("miragaia_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.MIRAGAIA, -8232382, -2635339, new Item.Properties()));
	public static final DeferredItem<Item> TUOJIANGOSAURUS_SPAWN_EGG = REGISTRY.register("tuojiangosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.TUOJIANGOSAURUS, -12042443, -16246141, new Item.Properties()));
	public static final DeferredItem<Item> TUOJIANGOSAURUS_FOSSIL = REGISTRY.register("tuojiangosaurus_fossil", TuojiangosaurusFossilItem::new);
	public static final DeferredItem<Item> PROTOCERATOPS_SPAWN_EGG = REGISTRY.register("protoceratops_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PROTOCERATOPS, -10205135, -11192007, new Item.Properties()));
	public static final DeferredItem<Item> ARCHAEOPTERYX_SPAWN_EGG = REGISTRY.register("archaeopteryx_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ARCHAEOPTERYX, -6190218, -16777216, new Item.Properties()));
	public static final DeferredItem<Item> PROTOCERATOPS_FOSSIL = REGISTRY.register("protoceratops_fossil", ProtoceratopsFossilItem::new);
	public static final DeferredItem<Item> ARCHAEOPTERYX_FOSSIL = REGISTRY.register("archaeopteryx_fossil", ArchaeopteryxFossilItem::new);
	public static final DeferredItem<Item> OLOROTITAN_SPAWN_EGG = REGISTRY.register("olorotitan_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.OLOROTITAN, -9346495, -1, new Item.Properties()));
	public static final DeferredItem<Item> OLOROTITAN_FOSSIL = REGISTRY.register("olorotitan_fossil", OlorotitanFossilItem::new);
	public static final DeferredItem<Item> EPHEDRA = block(DinosauriumModBlocks.EPHEDRA);
	public static final DeferredItem<Item> WELWITSCHIA = block(DinosauriumModBlocks.WELWITSCHIA);
	public static final DeferredItem<Item> MAGYAROSAURUS_SPAWN_EGG = REGISTRY.register("magyarosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.MAGYAROSAURUS, -39322, -1, new Item.Properties()));
	public static final DeferredItem<Item> NEMEGTOSAURUS_SPAWN_EGG = REGISTRY.register("nemegtosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.NEMEGTOSAURUS, -6710785, -1, new Item.Properties()));
	public static final DeferredItem<Item> MAGYAROSAURUS_FOSSIL = REGISTRY.register("magyarosaurus_fossil", MagyarosaurusFossilItem::new);
	public static final DeferredItem<Item> NEMEGTOSAURUS_FOSSIL = REGISTRY.register("nemegtosaurus_fossil", NemegtosaurusFossilItem::new);
	public static final DeferredItem<Item> PACHYRHINOSAURUS_SPAWN_EGG = REGISTRY.register("pachyrhinosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PACHYRHINOSAURUS, -8160935, -1, new Item.Properties()));
	public static final DeferredItem<Item> PACHYRHINOSAURUS_FOSSIL = REGISTRY.register("pachyrhinosaurus_fossil", PachyrhinosaurusFossilItem::new);
	public static final DeferredItem<Item> NANUQSAURUS_SPAWN_EGG = REGISTRY.register("nanuqsaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.NANUQSAURUS, -16777216, -1, new Item.Properties()));
	public static final DeferredItem<Item> NANUQSAURUS_FOSSIL = REGISTRY.register("nanuqsaurus_fossil", NanuqsaurusFossilItem::new);
	public static final DeferredItem<Item> PARAPUZOSIA_SPAWN_EGG = REGISTRY.register("parapuzosia_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PARAPUZOSIA, -65434, -52429, new Item.Properties()));
	public static final DeferredItem<Item> ORODROMEUS_SPAWN_EGG = REGISTRY.register("orodromeus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ORODROMEUS, -11584730, -4085101, new Item.Properties()));
	public static final DeferredItem<Item> PARAPUZOSIA_FOSSIL = REGISTRY.register("parapuzosia_fossil", ParapuzosiaFossilItem::new);
	public static final DeferredItem<Item> ORODROMEUS_FOSSIL = REGISTRY.register("orodromeus_fossil", OrodromeusFossilItem::new);
	public static final DeferredItem<Item> ANZU_SPAWN_EGG = REGISTRY.register("anzu_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ANZU, -10203593, -13145524, new Item.Properties()));
	public static final DeferredItem<Item> BEIPIAOSAURUS_SPAWN_EGG = REGISTRY.register("beipiaosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.BEIPIAOSAURUS, -1, -13421773, new Item.Properties()));
	public static final DeferredItem<Item> ANZU_FOSSIL = REGISTRY.register("anzu_fossil", AnzuFossilItem::new);
	public static final DeferredItem<Item> BEIPIAOSAURUS_FOSSIL = REGISTRY.register("beipiaosaurus_fossil", BeipiaosaurusFossilItem::new);
	public static final DeferredItem<Item> ZHENYUANLONG_SPAWN_EGG = REGISTRY.register("zhenyuanlong_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ZHENYUANLONG, -2203904, -1, new Item.Properties()));
	public static final DeferredItem<Item> ZHENYUANLONG_FOSSIL = REGISTRY.register("zhenyuanlong_fossil", ZhenyuanlongFossilItem::new);
	public static final DeferredItem<Item> DILOPHOSAURUS_SPAWN_EGG = REGISTRY.register("dilophosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.DILOPHOSAURUS, -14737099, -13420709, new Item.Properties()));
	public static final DeferredItem<Item> DILOPHOSAURUS_FOSSIL = REGISTRY.register("dilophosaurus_fossil", DilophosaurusFossilItem::new);
	public static final DeferredItem<Item> CEPHALOLEICHNITES_ITEM = REGISTRY.register("cephaloleichnites_item", CephaloleichnitesItemItem::new);
	public static final DeferredItem<Item> BUG_NET = REGISTRY.register("bug_net", BugNetItem::new);
	public static final DeferredItem<Item> OSMUNDA = block(DinosauriumModBlocks.OSMUNDA);
	public static final DeferredItem<Item> EDMONTOSAURUS_SPAWN_EGG = REGISTRY.register("edmontosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.EDMONTOSAURUS, -13395712, -1, new Item.Properties()));
	public static final DeferredItem<Item> EDMONTOSAURUS_FOSSIL = REGISTRY.register("edmontosaurus_fossil", EdmontosaurusFossilItem::new);
	public static final DeferredItem<Item> PACHYCEPHALOSAURUS_SPAWN_EGG = REGISTRY.register("pachycephalosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PACHYCEPHALOSAURUS, -6724096, -1, new Item.Properties()));
	public static final DeferredItem<Item> COELOPHYSIS_SPAWN_EGG = REGISTRY.register("coelophysis_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.COELOPHYSIS, -65536, -16776961, new Item.Properties()));
	public static final DeferredItem<Item> COELOPHYSIS_FOSSIL = REGISTRY.register("coelophysis_fossil", CoelophysisFossilItem::new);
	public static final DeferredItem<Item> CRETARANEUS_ITEM = REGISTRY.register("cretaraneus_item", CretaraneusItemItem::new);
	public static final DeferredItem<Item> MONGOLARACHNE_ITEM = REGISTRY.register("mongolarachne_item", MongolarachneItemItem::new);
	public static final DeferredItem<Item> LAUROZAMITES = block(DinosauriumModBlocks.LAUROZAMITES);
	public static final DeferredItem<Item> FRIED_SPIDER = REGISTRY.register("fried_spider", FriedSpiderItem::new);
	public static final DeferredItem<Item> SINEW = REGISTRY.register("sinew", SinewItem::new);
	public static final DeferredItem<Item> PYCNOFIBER = REGISTRY.register("pycnofiber", PycnofiberItem::new);
	public static final DeferredItem<Item> JEHOLOPTERUS_SPAWN_EGG = REGISTRY.register("jeholopterus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.JEHOLOPTERUS, -12109269, -3637120, new Item.Properties()));
	public static final DeferredItem<Item> HALSZKARAPTOR_SPAWN_EGG = REGISTRY.register("halszkaraptor_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.HALSZKARAPTOR, -7500403, -13553359, new Item.Properties()));
	public static final DeferredItem<Item> HALSZKARAPTOR_FOSSIL = REGISTRY.register("halszkaraptor_fossil", HalszkaraptorFossilItem::new);
	public static final DeferredItem<Item> JEHOLOPTERUS_FOSSIL = REGISTRY.register("jeholopterus_fossil", JeholopterusFossilItem::new);
	public static final DeferredItem<Item> PSITTACOSAURUS_SPAWN_EGG = REGISTRY.register("psittacosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PSITTACOSAURUS, -3407719, -10027162, new Item.Properties()));
	public static final DeferredItem<Item> YUTYRANNUS_SPAWN_EGG = REGISTRY.register("yutyrannus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.YUTYRANNUS, -10000537, -5661425, new Item.Properties()));
	public static final DeferredItem<Item> PSITTACOSAURUS_FOSSIL = REGISTRY.register("psittacosaurus_fossil", PsittacosaurusFossilItem::new);
	public static final DeferredItem<Item> YUTYRANNUS_FOSSIL = REGISTRY.register("yutyrannus_fossil", YutyrannusFossilItem::new);
	public static final DeferredItem<Item> REPENOMAMUS_SPAWN_EGG = REGISTRY.register("repenomamus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.REPENOMAMUS, -13421773, -1, new Item.Properties()));
	public static final DeferredItem<Item> REPENOMAMUS_FOSSIL = REGISTRY.register("repenomamus_fossil", RepenomamusFossilItem::new);
	public static final DeferredItem<Item> MAMENCHISAURUS_SPAWN_EGG = REGISTRY.register("mamenchisaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.MAMENCHISAURUS, -9154223, -2984677, new Item.Properties()));
	public static final DeferredItem<Item> MAMENCHISAURUS_FOSSIL = REGISTRY.register("mamenchisaurus_fossil", MamenchisaurusFossilItem::new);
	public static final DeferredItem<Item> SPINOFAARUS_SPAWN_EGG = REGISTRY.register("spinofaarus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.SPINOFAARUS, -12965619, -6386130, new Item.Properties()));
	public static final DeferredItem<Item> OMMA_ITEM = REGISTRY.register("omma_item", OmmaItemItem::new);
	public static final DeferredItem<Item> MASHED_BUGS = REGISTRY.register("mashed_bugs", MashedBugsItem::new);
	public static final DeferredItem<Item> NANNOGOMPHUS_ITEM = REGISTRY.register("nannogomphus_item", NannogomphusItemItem::new);
	public static final DeferredItem<Item> GIANT_CICADA_ITEM = REGISTRY.register("giant_cicada_item", GiantCicadItemItem::new);
	public static final DeferredItem<Item> LAMBEOSAURUS_SPAWN_EGG = REGISTRY.register("lambeosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.LAMBEOSAURUS, -9067850, -1, new Item.Properties()));
	public static final DeferredItem<Item> OURANOSAURUS_SPAWN_EGG = REGISTRY.register("ouranosaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.OURANOSAURUS, -6783362, -13555672, new Item.Properties()));
	public static final DeferredItem<Item> LAMBEOSAURUS_FOSSIL = REGISTRY.register("lambeosaurus_fossil", LambeosaurusFossilItem::new);
	public static final DeferredItem<Item> OURANOSAURUS_FOSSIL = REGISTRY.register("ouranosaurus_fossil", OuranosaurusFossilItem::new);
	public static final DeferredItem<Item> CRASSOSTREA_OYSTER = REGISTRY.register("crassostrea_oyster", CrassostreaOysterItem::new);
	public static final DeferredItem<Item> DSUNGARIPTERUS_SPAWN_EGG = REGISTRY.register("dsungaripterus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.DSUNGARIPTERUS, -13030369, -4081760, new Item.Properties()));
	public static final DeferredItem<Item> OYSTER_SOUP = REGISTRY.register("oyster_soup", OysterSoupItem::new);
	public static final DeferredItem<Item> RAW_OYSTER = REGISTRY.register("raw_oyster", RawOysterItem::new);
	public static final DeferredItem<Item> PTERODAUSTRO_SPAWN_EGG = REGISTRY.register("pterodaustro_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.PTERODAUSTRO, -6201505, -12632257, new Item.Properties()));
	public static final DeferredItem<Item> PTERODAUSTRO_FOSSIL = REGISTRY.register("pterodaustro_fossil", PterodaustroFossilItem::new);
	public static final DeferredItem<Item> DSUNGARIPTERUS_FOSSIL = REGISTRY.register("dsungaripterus_fossil", DsungaripterusFossilItem::new);
	public static final DeferredItem<Item> LISOWICIA_SPAWN_EGG = REGISTRY.register("lisowicia_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.LISOWICIA, -13421773, -3355648, new Item.Properties()));
	public static final DeferredItem<Item> LISOWICIA_FOSSIL = REGISTRY.register("lisowicia_fossil", LisowiciaFossilItem::new);
	public static final DeferredItem<Item> ALUMINIUM_INGOT = REGISTRY.register("aluminium_ingot", AluminiumIngotItem::new);
	public static final DeferredItem<Item> ALUMINIUM_BLOCK = block(DinosauriumModBlocks.ALUMINIUM_BLOCK);
	public static final DeferredItem<Item> BAUXITE_ORE = block(DinosauriumModBlocks.BAUXITE_ORE);
	public static final DeferredItem<Item> BAUXITE = REGISTRY.register("bauxite", BauxiteItem::new);
	public static final DeferredItem<Item> ALUMINIUM_NUGGET = REGISTRY.register("aluminium_nugget", AluminiumNuggetItem::new);
	public static final DeferredItem<Item> AMBER_FOSSIL = REGISTRY.register("amber_fossil", AmberFossilItem::new);
	public static final DeferredItem<Item> TIN_INGOT = REGISTRY.register("tin_ingot", TinIngotItem::new);
	public static final DeferredItem<Item> TIN_ORE = block(DinosauriumModBlocks.TIN_ORE);
	public static final DeferredItem<Item> TIN_BLOCK = block(DinosauriumModBlocks.TIN_BLOCK);
	public static final DeferredItem<Item> RAW_TIN = REGISTRY.register("raw_tin", RawTinItem::new);
	public static final DeferredItem<Item> BAUXITE_BLOCK = block(DinosauriumModBlocks.BAUXITE_BLOCK);
	public static final DeferredItem<Item> RAW_TIN_BLOCK = block(DinosauriumModBlocks.RAW_TIN_BLOCK);
	public static final DeferredItem<Item> DEEPSLATE_BAUXITE_ORE = block(DinosauriumModBlocks.DEEPSLATE_BAUXITE_ORE);
	public static final DeferredItem<Item> DEEPSLATE_TIN_ORE = block(DinosauriumModBlocks.DEEPSLATE_TIN_ORE);
	public static final DeferredItem<Item> BRONZE_INGOT = REGISTRY.register("bronze_ingot", BronzeIngotItem::new);
	public static final DeferredItem<Item> BRONZE_BLOCK = block(DinosauriumModBlocks.BRONZE_BLOCK);
	public static final DeferredItem<Item> BRONZE_PICKAXE = REGISTRY.register("bronze_pickaxe", BronzePickaxeItem::new);
	public static final DeferredItem<Item> BRONZE_AXE = REGISTRY.register("bronze_axe", BronzeAxeItem::new);
	public static final DeferredItem<Item> BRONZE_SWORD = REGISTRY.register("bronze_sword", BronzeSwordItem::new);
	public static final DeferredItem<Item> BRONZE_SHOVEL = REGISTRY.register("bronze_shovel", BronzeShovelItem::new);
	public static final DeferredItem<Item> BRONZE_HOE = REGISTRY.register("bronze_hoe", BronzeHoeItem::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_HELMET = REGISTRY.register("bronze_armor_helmet", BronzeArmorItem.Helmet::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_CHESTPLATE = REGISTRY.register("bronze_armor_chestplate", BronzeArmorItem.Chestplate::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_LEGGINGS = REGISTRY.register("bronze_armor_leggings", BronzeArmorItem.Leggings::new);
	public static final DeferredItem<Item> BRONZE_ARMOR_BOOTS = REGISTRY.register("bronze_armor_boots", BronzeArmorItem.Boots::new);
	public static final DeferredItem<Item> FRAMED_GLASS = block(DinosauriumModBlocks.FRAMED_GLASS);
	public static final DeferredItem<Item> TIN_TILES = block(DinosauriumModBlocks.TIN_TILES);
	public static final DeferredItem<Item> CUT_TIN = block(DinosauriumModBlocks.CUT_TIN);
	public static final DeferredItem<Item> CUT_TIN_STAIRS = block(DinosauriumModBlocks.CUT_TIN_STAIRS);
	public static final DeferredItem<Item> CUT_TIN_SLAB = block(DinosauriumModBlocks.CUT_TIN_SLAB);
	public static final DeferredItem<Item> CHISELED_TIN = block(DinosauriumModBlocks.CHISELED_TIN);
	public static final DeferredItem<Item> WOODEN_KNIFE = REGISTRY.register("wooden_knife", WoodenKnifeItem::new);
	public static final DeferredItem<Item> STONE_KNIFE = REGISTRY.register("stone_knife", StoneKnifeItem::new);
	public static final DeferredItem<Item> GOLDEN_KNIFE = REGISTRY.register("golden_knife", GoldenKnifeItem::new);
	public static final DeferredItem<Item> IRON_KNIFE = REGISTRY.register("iron_knife", IronKnifeItem::new);
	public static final DeferredItem<Item> BRONZE_KNIFE = REGISTRY.register("bronze_knife", BronzeKnifeItem::new);
	public static final DeferredItem<Item> DIAMOND_KNIFE = REGISTRY.register("diamond_knife", DiamondKnifeItem::new);
	public static final DeferredItem<Item> NETHERITE_KNIFE = REGISTRY.register("netherite_knife", NetheriteKnifeItem::new);
	public static final DeferredItem<Item> HORSESHOE_CRAB_SPAWN_EGG = REGISTRY.register("horseshoe_crab_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.HORSESHOE_CRAB, -12041678, -12962260, new Item.Properties()));
	public static final DeferredItem<Item> HORSESHOE_CRAB_BLOOD = REGISTRY.register("horseshoe_crab_blood", HorseshoeCrabBloodItem::new);
	public static final DeferredItem<Item> ANCHIORNIS_SPAWN_EGG = REGISTRY.register("anchiornis_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ANCHIORNIS, -13421773, -5492719, new Item.Properties()));
	public static final DeferredItem<Item> ANCHIORNIS_FOSSIL = REGISTRY.register("anchiornis_fossil", AnchiornisFossilItem::new);
	public static final DeferredItem<Item> HERRERASAURUS_SPAWN_EGG = REGISTRY.register("herrerasaurus_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.HERRERASAURUS, -1787527, -10728647, new Item.Properties()));
	public static final DeferredItem<Item> SHAROVIPTERYX_SPAWN_EGG = REGISTRY.register("sharovipteryx_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.SHAROVIPTERYX, -6710785, -10066177, new Item.Properties()));
	public static final DeferredItem<Item> ARAUCARIA_WOOD = block(DinosauriumModBlocks.ARAUCARIA_WOOD);
	public static final DeferredItem<Item> ARAUCARIA_LOG = block(DinosauriumModBlocks.ARAUCARIA_LOG);
	public static final DeferredItem<Item> ARAUCARIA_PLANKS = block(DinosauriumModBlocks.ARAUCARIA_PLANKS);
	public static final DeferredItem<Item> ARAUCARIA_LEAVES = block(DinosauriumModBlocks.ARAUCARIA_LEAVES);
	public static final DeferredItem<Item> ARAUCARIA_STAIRS = block(DinosauriumModBlocks.ARAUCARIA_STAIRS);
	public static final DeferredItem<Item> ARAUCARIA_SLAB = block(DinosauriumModBlocks.ARAUCARIA_SLAB);
	public static final DeferredItem<Item> ARAUCARIA_FENCE = block(DinosauriumModBlocks.ARAUCARIA_FENCE);
	public static final DeferredItem<Item> ARAUCARIA_FENCE_GATE = block(DinosauriumModBlocks.ARAUCARIA_FENCE_GATE);
	public static final DeferredItem<Item> ARAUCARIA_PRESSURE_PLATE = block(DinosauriumModBlocks.ARAUCARIA_PRESSURE_PLATE);
	public static final DeferredItem<Item> ARAUCARIA_BUTTON = block(DinosauriumModBlocks.ARAUCARIA_BUTTON);
	public static final DeferredItem<Item> HERRERASAURUS_FOSSIL = REGISTRY.register("herrerasaurus_fossil", HerrerasaurusFossilItem::new);
	public static final DeferredItem<Item> SHAROVIPTERYX_FOSSIL = REGISTRY.register("sharovipteryx_fossil", SharovipteryxFossilItem::new);
	public static final DeferredItem<Item> ARAUCARIA_DOOR = doubleBlock(DinosauriumModBlocks.ARAUCARIA_DOOR);
	public static final DeferredItem<Item> ARAUCARIA_TRAPDOOR = block(DinosauriumModBlocks.ARAUCARIA_TRAPDOOR);
	public static final DeferredItem<Item> ARAUCARIA_SAPLING = block(DinosauriumModBlocks.ARAUCARIA_SAPLING);
	public static final DeferredItem<Item> OSMUNDA_ROOT = REGISTRY.register("osmunda_root", OsmundaRootItem::new);
	public static final DeferredItem<Item> OSMUNDA_BREAD = REGISTRY.register("osmunda_bread", OsmundaBreadItem::new);
	public static final DeferredItem<Item> UNFIRED_TEACUP = REGISTRY.register("unfired_teacup", UnfiredTeacupItem::new);
	public static final DeferredItem<Item> TEACUP = REGISTRY.register("teacup", TeacupItem::new);
	public static final DeferredItem<Item> WATER_CUP = REGISTRY.register("water_cup", WaterCupItem::new);
	public static final DeferredItem<Item> LAUROZAMITES_LEAVES = REGISTRY.register("laurozamites_leaves", LaurozamitesLeavesItem::new);
	public static final DeferredItem<Item> UNBOILED_LAUROZAMITES_TEA = REGISTRY.register("unboiled_laurozamites_tea", UnboiledLaurozamitesTeaItem::new);
	public static final DeferredItem<Item> LAUROZAMITES_TEA = REGISTRY.register("laurozamites_tea", LaurozamitesTeaItem::new);
	public static final DeferredItem<Item> ONCHOPRISTIS_FOSSIL = REGISTRY.register("onchopristis_fossil", OnchopristisFossilItem::new);
	public static final DeferredItem<Item> CEPHALOLEICHNITES_FOSSIL = REGISTRY.register("cephaloleichnites_fossil", CephaloleichnitesFossilItem::new);
	public static final DeferredItem<Item> CRETARANEUS_FOSSIL = REGISTRY.register("cretaraneus_fossil", CretaraneusFossilItem::new);
	public static final DeferredItem<Item> MONGOLARACHNE_FOSSIL = REGISTRY.register("mongolarachne_fossil", MongolarachneFossilItem::new);
	public static final DeferredItem<Item> RESURRECTION_ALTAR = block(DinosauriumModBlocks.RESURRECTION_ALTAR);
	public static final DeferredItem<Item> BARYONYX_SPAWN_EGG = REGISTRY.register("baryonyx_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.BARYONYX, -10591673, -14079965, new Item.Properties()));
	public static final DeferredItem<Item> BARYONYX_FOSSIL = REGISTRY.register("baryonyx_fossil", BaryonyxFossilItem::new);
	public static final DeferredItem<Item> MOSSY_DIRT = block(DinosauriumModBlocks.MOSSY_DIRT);
	public static final DeferredItem<Item> LIVERWORTS = block(DinosauriumModBlocks.LIVERWORTS);
	public static final DeferredItem<Item> ZBY_SPAWN_EGG = REGISTRY.register("zby_spawn_egg", () -> new DeferredSpawnEggItem(DinosauriumModEntities.ZBY, -7048615, -1, new Item.Properties()));
	public static final DeferredItem<Item> ZBY_FOSSIL = REGISTRY.register("zby_fossil", ZbyFossilItem::new);
	public static final DeferredItem<Item> TIME_MACHINE = REGISTRY.register("time_machine", TimeMachineItem::new);

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static DeferredItem<Item> doubleBlock(DeferredHolder<Block, Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}
}
